name: restaurant-manager

services:
  db:
    image: postgres:16-alpine
    container_name: restaurant-manager-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurant_manager
    ports:
      - "5433:5432" # Mapea el puerto de tu PC al contenedor
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restaurant_manager"]
      interval: 5s
      timeout: 5s
      retries: 20

  migrator:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: restaurant-manager-migrator
    working_dir: /src
    volumes:
      - ./:/src
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -lc
      "dotnet tool install --global dotnet-ef --version 10.0.7 || dotnet tool update --global dotnet-ef --version 10.0.7 &&
       export PATH=\"$$PATH:/root/.dotnet/tools\" &&
       dotnet restore RestaurantManager.Api/RestaurantManager.Api.csproj &&
       dotnet ef database update --project RestaurantManager.Infrastructure --startup-project RestaurantManager.Api --context RestaurantManagerDbContext --connection \"Host=db;Port=5432;Database=restaurant_manager;Username=postgres;Password=admin\""
    restart: "no"

volumes:
  pgdata: